#	dockerfile .
	FROM ubuntu:latest
	
	#install necessary package
	RUN DEBIAN_FRONTEND=noninteractive \
		apt-get update && \
		apt-get clean && \
		apt-get install -y wget bzip2 make unzip cppcheck\
		build-essential \
		curl
		
		
	#Create a non-root user named "ubuntu"
	#But put in root group since Github actions needs permissions
	#to create tmp files.
	RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo \
		-u 1001 ubuntu
	USER ubuntu
	WORKDIR /home/ubuntu
	#ADD . /home/ubuntu
	

