on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: abdolkarimhashemi/arm-gnu-toolchain-13.2rel1:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: make
      - run: make cppcheck
      - run: make flash
